name: Build/release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v7
        with:
          node-version: 26

      - name: NPM Package install
        run: npm install

      - name: NPM Build Binaries
        run: npx electron-builder

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v6
        with:
          name: binaries-${{ matrix.os }}
          path: |
            dist/*.AppImage
            dist/*.exe
          retention-days: 30

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.AppImage
            dist/*.exe
